### ISSUE TITLE
Link to podcast

### ISSUE THREAD

**Issue by scordle** [wwiley3528/CSC322-202fall#5]
@wwiley3528 - On your index.html, it would be good to add a link to your podcast.  I added the <a> tag, but you will need to add the URL.  If you have any other sites, or pages that showcase your work or monetize your products, include them as well.  Remember, this page is about you and your work.

**Comment by scordle** [comment]
This still need some work.  When I click the link, I get an XML page instead of the podcast.

**Comment by wwiley3528** [comment]
Updated link
